# Generated by Django 3.1.7 on 2021-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funds_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10000000000)),
                ('name', models.CharField(max_length=10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)),
            ],
        ),
    ]
